### ISSUE TITLE
23h2 fonts?

### ISSUE THREAD

**Issue by idontveapc** [CNMan/WindowsFonts#1]
windows 23h2 preview was released on 26 sep.

**Comment by CNMan** [comment]
https://github.com/CNMan/WindowsFonts/commit/ed18bd07490895d67e4f3720424ede4d421fc3a8
updated to latest build.

**Comment by idontveapc** [comment]
Any updates?

**Comment by CNMan** [comment]
@idontveapc updated to latest build.
